# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Counts <- function(tax, bin) {
    .Call(`_divDyn_Counts`, tax, bin)
}

CRbinwise <- function(binVar, quota, seed) {
    .Call(`_divDyn_CRbinwise`, binVar, quota, seed)
}

seqduplicated <- function(vect) {
    .Call(`_divDyn_seqduplicated`, vect)
}

fillLogical <- function(logic, dir) {
    .Call(`_divDyn_fillLogical`, logic, dir)
}

fillCharacter <- function(stri, dir) {
    .Call(`_divDyn_fillCharacter`, stri, dir)
}

fillNumeric <- function(num, dir, inc) {
    .Call(`_divDyn_fillNumeric`, num, dir, inc)
}

