# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Counts <- function(tax, bin) {
    .Call('_divDyn_Counts', PACKAGE = 'divDyn', tax, bin)
}

CRbinwise <- function(binVar, quota) {
    .Call('_divDyn_CRbinwise', PACKAGE = 'divDyn', binVar, quota)
}

